export default tempData = [
  {
    name: "Study for exam",
    date: "November 12, 2023",
    time: "12:23 pm",
    priority: "High",
    priorityColor: "#F76C5E",
    color: "#586BA4",
    completed: false,
  },
  {
    name: "Go to the store",
    date: "May 12, 2023",
    time: "09:23 am",
    priority: "Medium",
    priorityColor: "#FFA552",
    color: "#F5DD90",
    completed: false,
  },
  {
    name: "Get chipotle",
    date: "April 12, 2023",
    time: "12:01 pm",
    priority: "Low",
    priorityColor: "#B6EEA6",
    color: "#84DCCF",
    completed: true,
  },
  {
    name: "walk the dog",
    date: "November 12, 2023",
    time: "12:23 pm",
    priority: "High",
    priorityColor: "#F76C5E",
    color: "#586BA4",
    completed: true,
  },
  {
    name: "take my meds",
    date: "May 12, 2023",
    time: "09:23 am",
    priority: "Medium",
    priorityColor: "#FFA552",
    color: "#F5DD90",
    completed: false,
  },
  {
    name: "soccer practice",
    date: "April 12, 2023",
    time: "12:01 pm",
    priority: "Low",
    priorityColor: "#B6EEA6",
    color: "#84DCCF",
    completed: true,
  },
];
